#!/bin/sh

set -eu

LARK_SCRIPT_DIRECTORY="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
LARK_EXECUTABLE="$(/bin/sh "${LARK_SCRIPT_DIRECTORY}/install-lark-cli.sh")"

unset LARKSUITE_CLI_USER_ACCESS_TOKEN LARKSUITE_CLI_BRAND LARKSUITE_CLI_APP_ID
export LARKSUITE_CLI_NO_UPDATE_NOTIFIER=1
export LARKSUITE_CLI_NO_SKILLS_NOTIFIER=1
exec "${LARK_EXECUTABLE}" "$@"
